apiVersion: v1
kind: Service
metadata:
  name: cv-job-matching-api
spec:
  selector:
    app: cv-job-matching-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
